### ISSUE TITLE
I'm having issues putting in images

### ISSUE THREAD

**Issue by CWelch04** [Montana-Media-Arts/120_CreativeCoding1-Fall2022-Samples#3]
I have two images from my computer files that I want to put in for the project, but when I go to look at my pages online, they don't show up. I'm not sure what I'm doing wrong. I double checked the code on the course website, and it looked right.

**Comment by Brit0331** [comment]
Did you double-check the file structure? sounds like a problem with your <a href

**Comment by CWelch04** [comment]
<img src="20221005_120553.jpg"/> is what I'm putting in.

**Comment by CWelch04** [comment]
<img src="20221005_120553. jpg"/> is what I'm using

**Comment by CWelch04** [comment]
![image](https://user-images.githubusercontent.com/112434467/194649247-97ca9f49-3cdc-4180-be24-75140c610b16.png)

**Comment by Brit0331** [comment]
are the images in the same folder as your .HTML file? if they are then the correct tag would be removing the /. so <img src="yourimage.jpg"> 
If they are in another folder you have to link to that folder in the src= 
for example: I have an images folder inside my Homework 6 folder so I have to link them like src="images/myimage.jpg"

**Comment by CWelch04** [comment]
Thanks! That fixed it. I didn't have the paths in.

**Comment by Brit0331** [comment]
Do you wanna call on discord and talk?

Sent from my iPhone

On Oct 6, 2022, at 3:28 PM, CWelch04 ***@***.***> wrote:

﻿

I have two images from my computer files that I want to put in for the project, but when I go to look at my pages online, they don't show up. I'm not sure what I'm doing wrong. I double checked the code on the course website, and it looked right.
